import type { GetServerSideProps, NextPage } from 'next'
import { getSession, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from 'styles/Home.module.css'

// export const getServerSideProps: GetServerSideProps = async (context) => {
//   const session = await getSession(context)

//   if (!session) {
//     return {
//       redirect: {
//         destination: '/login',
//         permanent: false
//       }
//     }
//   }
 
//   return {
//     props: {
//       session
//     }
//   }

// }

const Home: NextPage = () => {

  /*

  Sem usar o getServerSideProps

  import useRequiredAuth from 'lib/useRequiredAuth'

  const session = useRequiredAuth()

  if (!session) {
    return (
      <div>Loading...</div>
    )
  }
  */

  const { data: session } = useSession()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to my application, {session?.user.name || 'Desconhecido'}!</h1>

      <button type="button" className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
        <Link href="/login">Login</Link>
      </button>

      <button onClick={() => signOut()} type="button" className="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">
        Logout
      </button>

    </div>
  )
}

export default Home
